name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.2
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  intl: ^0.19.0
  file_picker: ^6.1.1
  path: ^1.8.3
  uuid: ^4.2.2
  image_picker: ^1.0.7
  emoji_picker_flutter: ^2.2.0
  audioplayers: ^5.2.1
  dio: ^5.4.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
